import json
from typing import Any
from .qos_manager import QoSLevel


class NatsPublisher:
    """
    Publishes structured messages to NATS or JetStream based on QoS header.
    Expects payloads generated by MessageFactory (dict with header + body).
    """

    def __init__(self, client):
        """
        :param client: A connected NATS client instance.
                       Must expose publish() and js_publish() if JetStream is used.
        """
        self.client = client

    async def publish(self, subject: str, msg: dict):
        """
        Publish message using QoS level in header.
        :param subject: NATS subject to publish on.
        :param msg: Message dict as returned by MessageFactory.
        """
        # Validate payload structure
        if not isinstance(msg, dict) or "header" not in msg or "body" not in msg:
            raise TypeError("Invalid message: must contain 'header' and 'body' fields.")

        header = msg["header"]
        qos = header.get("qos", QoSLevel.AT_MOST_ONCE)
        msg_id = header.get("msg_id")
        stream = header.get("stream")  # Optional, for JetStream
        data = json.dumps(msg).encode("utf-8")

        # QoS-level routing
        if qos == QoSLevel.AT_MOST_ONCE:
            # Simple fire-and-forget NATS publish
            await self.client.nc.publish(subject, data)

        elif qos == QoSLevel.AT_LEAST_ONCE:
            # JetStream publish, ensures message persistence and ack
            if not stream:
                raise ValueError("Stream name required for QoS >= 1")
            ack = await self.client.js.js_publish(
                stream=stream,
                subject=subject,
                payload=data,
                msg_id=msg_id,
            )
            return ack

        elif qos == QoSLevel.EXACTLY_ONCE:
            # Deduplicated, acked publish (requires stream + msg_id)
            if not stream or not msg_id:
                raise ValueError("Stream + msg_id required for QoS EXACTLY_ONCE")
            ack = await self.client.js_publish(
                stream=stream,
                subject=subject,
                payload=data,
                msg_id=msg_id,
            )
            return ack

        else:
            raise ValueError(f"Unsupported QoS level: {qos}")

        return None

